language: node_js
node_js:
  - "6"
  - "6.2"
  - "6.1"
  - "6.0"
  - "5"
  - "5.11"
  # - "5.1"
  # - "4"
  # - "4.2"
  # - "4.1"
  # - "4.0"
  # - "0.12"
  # - "0.11"
  # - "0.10"
  # - "0.8"
  # - "0.6"
  # - "iojs"
script: npm run travisci
